hmrc/plastic-packaging-tax-registration

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/FullName.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositoryItSpec.scala
This was optional to allow for partial validation.
We will try to review this at a later stage.
> PPTP-428 Make FirstName and LastName mandatory

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
A `SafeNumber` may be returned by the relevant GRS microservice, if a
legal entity has been successfuly registered by the GRS service.
> PTPP-836 Add safeNumber to OrganisationDetails

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/SoleTraderIncorporationDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
Provide `SAUTR` as the second optional value to EIS/IF as date of birth
is incorrect as it not even passes the schema validation
> PPTP-360 Correctly support Sole Trader subscription

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/EISResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/EISSubscriptionCreateSuccessfulResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionCreateWithNrsFailureResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionCreateWithNrsSuccessfulResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/nrs/NrsFailureResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/nrs/NrsResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/nrs/NrsSuccessfulResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
As part of the NRS work we need to CiP/TxM audit the `nrSubmissionId` or
the NRS failure reason.
This is passed to the FE, where the CiP audit currently lives.
> PPTP-994 Make NRS submissinId/failureReason available to FE

- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
Update application library dependencies
Fixed config warnings
```
2021-09-23 08:36:35,234 level=[WARN] logger=[uk.gov.hmrc.play.bootstrap.config.DeprecatedConfigChecker] thread=[play-dev-mode-akka.actor.default-dispatcher-8] rid=[] user=[] message=[The key 'play.modules.enabled' is configured with value 'uk.gov.hmrc.play.bootstrap.AuditModule', which is deprecated. Please use 'uk.gov.hmrc.play.audit.AuditModule' instead.] 
2021-09-23 08:36:37,149 level=[WARN] logger=[uk.gov.hmrc.play.bootstrap.backend.filters.BackendFilters] thread=[play-dev-mode-akka.actor.default-dispatcher-8] rid=[] user=[] message=[play.http.filters = "uk.gov.hmrc.play.bootstrap.backend.filters.BackendFilters" is no longer required and can be removed. Filters are configured using play's default filter system: …
```
> PPTP-1210 - Update application library dependencies

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionCreateFailureResponseWithStatusCode.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
We need to inform the user of duplicate subscription failures when we attempt to create the PPT subscription. We communicate EIS subscription failure responses to the registration front end so that it can decide how to deal with them.
Associated FE change:
> PPTP-1205 : Alert of Duplicate Subscriptions

- build.sbt
There is a known issue where JUnit reporters can mangle test output files when jobs are run in parallel.
> BAU : Disable the JUnit XML report plugin

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscriptionStatus/ETMPSubscriptionStatusResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscriptionStatus/SubscriptionStatus.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscriptionStatus/SubscriptionStatusResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscriptionStatus/SubscriptionStatusResponseSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
Create a simplified SubscriptionStatusResponse that is aligned with the needs of the FE service
> PPTP-1211 - simplify SubscriptionStatusResponse

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrincipalPlaceOfBusinessDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositorySpec.scala
Update PrimaryContactDetails Address model to make line 2 non-optional
- remove fix replacing empty line 2 with a space
> PPTP-1150 - make PPT address line 2 non-optional

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
Bring organisation type enum in line with front-end
Depends on FE PR - https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/239
> PPTP-1162 - new organisation type

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrincipalPlaceOfBusinessDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositorySpec.scala
NOTE:  With this implementation the "town" value that we capture will not always be sent to EIS as "addressLine4" - it might be addressLine2, addressLine3 or addressLine4 depending on the number of lines captured.
> PPTP-1243 - support for optional address line 2

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
Change "Overseas" to "OverseasCompanyUkBranch" to make intention clearer
Results in submission to EIS that looks like this 
```
"legalEntityDetails" : {
"dateOfApplication" : "2021-11-22",
"customerIdentification1" : "01234567",
"customerIdentification2" : "1234567890",
"customerDetails" : {
"customerType" : "Organisation",
"organisationDetails" : {
"organisationType" : "OverseasCompanyUkBranch",
"organisationName" : "Test Company Ltd"
}
},
```
Requires - matching FE change - https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/267
> PPTP-1288 - Integrate with Non UK company with UK Establishment

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrincipalPlaceOfBusinessDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PPTAddress.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/GroupMember.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositorySpec.scala
Renamed Address => PPTAddress - this is the FE address used in the Registration model
AddressDetails is the "EIS" address used in the subscription create request
Group member addresses are now sent from FE as a PPTAddress for consistency.
FE changes - https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/274
> BAU - refactor Address models to simplify and remove redundant code

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/GroupDetail.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/GroupError.scala
Add optional `GroupError` type to `GroupDetail` model
Required for FE change - TBC
> PPTP-1432 - Groups - 7B. Errors - Organisation already added to group

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnerContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
FE PR: https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/316
> PPTP-1595 : Registration Model Update to Support Partnerships

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
Partner.partnerType is the canonical field for partner type.
Removing this field does not effect the acceptance tests.
> Remove unused Partner.partnerPartershipDetails.partnershipType field

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationRequest.scala
Added Registration.dateOfRegistration to both FE and BE as required to be displayed on this page.
FE: https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/352
> PPTP-1673 : Refactor Main Amend Registration Page

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationRequest.scala
FE: https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/353
> PPTP-1678 : Ensure Registration Changes Backwards Compatible

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
When unmashalling an EMTP Subscription back into a Registration, attempt to re hydrate a Partnership's Partners from Subscription GroupPartnershipSubscription
> PPTP-1682 Map Subscription partners back to Registration

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
Set hard coded mandatory change of circumstances on subscription updates.
> Pptp 1765 Set hard coded mandatory change of circumstances on subscription updates

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
Since LegalEntityDetails.regWithoutID is always true for group subscriptions, we can (when creating a Registration from a Subscription) use the Registration equivalent field (OrganisationDetails.regWithoutIDFlag) to hold the value for the representative group member (the first GroupPartnershipDetails instance). When re-creating the Subscription from the amended Registration we will set LegalEntityDetails.regWithoutID to true (since it's always this value) and use the value in OrganisationDetails.regWithoutIDFlag to populate the representative group member (the first GroupPartnershipDetails instance). Other group members can then be populated from the GroupMember instances.
See https://jira.tools.tax.service.gov.uk/browse/PPTP-1803 for a schematic showing this.
> PPTP-1803 : RegWithoutID Fix

- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/DeregistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/DeregistrationReason.scala
- build.sbt
- conf/app.routes
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/DeregistrationControllerSpec.scala
New endpoint to support deregistration.
> PPTP-1880: Deregistration

- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/actions/Authenticator.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/actions/AuthenticatorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/AuthTestSupport.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
Registration backend end points which are specific to a given ppt enrolment should be authed for that enrolment.
Prevents cross account access.
Authenticator introduces an option parameter to enforce this. Applies to Subscription end points. Include support for an Agent delegated auth.
> PPTP-1854 Registration backend end points which are specific to a given ppt enrolment should be authed for that enrolment

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/validation/JsonSchemaError.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/services/SubscriptionService.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/util/Obfuscation.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/validators/PptSchemaValidator.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/validators/PptSchemaValidatorSpec.scala
Logging is configured in production at WARN level except for loggers that start with `uk.gov.hmrc.plasticpackagingtaxregistration`.
> removed logger prefix that was causing logs to not appear

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetailsSpec.scala
GForm ppt registrations have been manually setting organisationType as 'LIMITED COMPANY'. 
We don't support this type so this change will default organisationType to "OverseasCompanyUkBranch" when it cannot be read into the types we support as is done on the frontend in some places.
Any amendments will take "OverseasCompanyUkBranch" as the organisationType. Not sure if this would result in a failure on an update or not but at least it resolves the user being able to see their account details.
> fallback org type of OverseasCompanyUkBranch for gform subscriptions
