hmrc/plastic-packaging-tax-registration

- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtaxregistration/builders/RegistrationRequestBuilder.scala
* Support Primary Contact Address details
* BAU - Clear Compilation Warnings
> PPTP-434 Support Primary Contact Address details

- app/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/TTLIndexing.scala
Due to hmrc constraints where we use standard mongo roles for permission management we don't have a way to add specific commands to existing predefined roles. Therefore the only way to update ttl on this index is through dropping it and recreating with new ttl.
> PPTP-806: replaced update index for drop index

- app/uk/gov/hmrc/plasticpackagingtaxregistration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/NonRepudiationConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionCreateFailureResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionCreateSuccessfulResponse.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationRequest.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/nrs/IdentityData.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/nrs/NonRepudiationMetadata.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/nrs/NonRepudiationSubmissionAccepted.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/services/nrs/NonRepudiationService.scala
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/AuthTestSupport.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/AuthTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/NrsTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/it/ConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/unit/ControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/builders/RegistrationRequestBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/NonRepudiationConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/services/nrs/NonRepudiationServiceSpec.scala
NRS stands for Non Repudiation Service
Also involved is to separate successful fields from the failures, this provides us with a cleaner interface
> PPTP-752 Integrate with NRS 

- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/actions/Authenticator.scala
- build.sbt
- test/uk/gov/hmrc/plasticpackagingtaxregistration/actions/AuthenticatorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/AuthTestSupport.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
Also Increase code coverage threshold.
> PPTP-893 Use 'InternalId' to save registration progress 

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
Updated the scottish partnership details to Legal entity details.
> PPTP-1015 Added scottish partnership journey

- app/uk/gov/hmrc/plasticpackagingtaxregistration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscriptionStatus/ETMPSubscriptionChannel.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnectorISpec.scala
Updated Get Subscription Status (API 1534) to v2.2.0
Corrected regime to PPT in context path for subscription status
> PPTP-1209 Updated Get Subscription Status (API 1534) to v2.2.0

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
> PPTP-1225 Addressline2 populated with space when blank

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositorySpec.scala
Remove organisation based in UK page
Requires https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/56 and https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/172
> PPTP-1226 - remove organisation based in UK page

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/TaxEnrolmentsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/UserEnrolmentController.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/services/nrs/NonRepudiationService.scala
Intent is to have enough info level logging in prod to help with problem diagnosis.
> Additional logging for prod

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/EISConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
> Fix correlationId logging

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/GroupDetail.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegType.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationRequest.scala
Added registration type (group or single entity) and group detail to Registration.
> PPTP-13381 : Registration type and group detail

- conf/application-json-logger.xml
Create custom logger for ppt classes (packages)
> BAU - custom logger for ppt classes

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/AddressDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/GroupMember.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/OrganisationDetails.scala
Initial model for group member list storage
> PPTP-1409 - basic model for list of group members

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
> PPTP-1186 - Added new org type

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/GroupMember.scala
Assoc FE PR: https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/250
> PPTP-1396 : Add id to GroupMember

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/GroupDetail.scala
> PPTP-1141- Added current member organisation type

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/OrganisationDetails.scala
> PPTP-1407 Added business partner id to organisationDetails

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
> BAU - fix for broken build - address construction

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrincipalPlaceOfBusinessDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositorySpec.scala
Dependent FE/AT changes: 
* https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/272
* https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/74
> PPTP-1484 : Support non-uk addresses

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/GroupError.scala
> PPTP-1306 Added member already registered to the group error type

- project/AppDependencies.scala
- project/plugins.sbt
> BAU - dependency update

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/ChangeOfCircumstanceDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/group/GroupMember.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/PPTAddressSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> PPTP-1519 Added tests

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
> PPTP-1167 updated PartnershipDetails with IncorporatedPartnershipDetails

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
More accurate logging for groups.
Raised alert level when sub create call fails to trigger alert
> Better logging

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/SoleTraderIncorporationDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
> PPTP-1176 - Sole Trader - Happy path with no nino

- app/uk/gov/hmrc/plasticpackagingtaxregistration/util/remove/RegistrationRemoval.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/util/remove/RegistrationRemovalModule.scala
- build.sbt
- conf/application.conf
Addition of temporary code to remove in-flight registrations
> PPTP-1600: remove in-flight registrations

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
> PPTP-1191 Select nominated partner org type

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
> PPTP-1594 : Registration Model Update to Support Partnerships

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
> PPTP-1650 LLP Registration Failed

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/ContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrimaryContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrincipalPlaceOfBusinessDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- build.sbt
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/builders/RegistrationBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/ContactDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrimaryContactDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/PrincipalPlaceOfBusinessDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> PPTP-1590 : Partnership Subscriptions

- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
Resolve clash between 2 most recent merges.
> Rebase clash

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnershipDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
> PPTP-1658 Fixed Group - LLP Registration Failed

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
Support newly added group members when transforming registrations to PPT subscriptions.
> PPTP-1420 : Post Registration - Add New Group Member

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Partner.scala
> PPTP-1635 Registered society added to list of partners

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
Persist Registration fields which are used the the temporary storage of email verification journey details.
> New registration can persist inflight email verification journey details

- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/DeregistrationController.scala
- conf/app.routes
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/DeregistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/DeregistrationReasonSpec.scala
> PPTP-1787 Update with deregistration details and call to NRS

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/LiabilityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
> Fix - post-launch field not getting mapped to correct field on API call

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
> PPTP-1663-merge-fixes

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/IncorporationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/builders/IncorporationDetailsBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/PartnerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
Enable gforms users to log into the service and see their subscription details / submit amendments.
> Added support for gform registered entities

- app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/UserEnrolmentController.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/UserEnrolmentControllerSpec.scala
Removed ES20 call as it will be performed as part of ES8
This should resolve known facts mismatch issue where > 50 records returned on a get known facts call (ES20) with only a reg date.
> Removed ES20 call as it will be performed as part of ES8

- app/uk/gov/hmrc/plasticpackagingtaxregistration/models/LiabilityDetails.scala
> Add isNewLiability property to LiabilityDetails model

- app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnector.scala
> PPTP-2496 | clense json of illegal characters

- app/repositories/RegistrationRepository.scala
- conf/application.conf
- precheck.sh
- project/build.properties
- project/plugins.sbt
> PPTP-2804 - App dependency updates

- app/controllers/UserEnrolmentController.scala
- app/models/nrs/IdentityData.scala
- app/services/nrs/NonRepudiationService.scala
- app/validators/PptSchemaValidator.scala
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/NrsTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/services/SubscriptionServiceSpec.scala
> upgraded scala to 2.13.10

- app/models/PPTAddress.scala
- app/models/Registration.scala
- app/models/eis/subscription/group/GroupPartnershipDetails.scala
- app/models/eis/subscription/group/GroupPartnershipSubscription.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/SubscriptionTestData.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/SubscriptionSpec.scala
> PPTP-2930 | live handover | floating strings to enums

- conf/application-json-logger.xml
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
> PPTP-2935 | live handover | update dependancies

- app/controllers/actions/Authenticator.scala
- app/repositories/RegistrationRepository.scala
- app/services/SubscriptionService.scala
> PPTP-2948 | live handover | update log levels

- app/connectors/EnrolmentStoreProxyConnector.scala
- app/models/EnrolmentStatus.scala
- app/models/Registration.scala
- app/models/eis/subscription/CustomerType.scala
- app/models/eis/subscription/LegalEntityDetails.scala
- app/models/eis/subscription/Subscription.scala
- app/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/services/nrs/NonRepudiationService.scala
- project/AppDependencies.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/EnrolmentStoreProxyConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/AddressDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/BusinessCorrespondenceDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/services/SubscriptionServiceSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/validators/PptSchemaValidatorSpec.scala
> PPTP-2937 | Live handover | resolve warnings

- app/connectors/NonRepudiationConnector.scala
- app/connectors/SubscriptionsConnector.scala
- app/models/Partner.scala
- app/models/Registration.scala
- app/models/eis/subscription/group/GroupPartnershipSubscription.scala
- app/models/eis/subscriptionStatus/ETMPSubscriptionStatusResponse.scala
- build.sbt
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/GroupPartnershipSubscriptionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/OrganisationDetailsSpec.scala
> PPTP-2932 | Live handover | resolve todos

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/builders/RegistrationBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtaxregistration/repositories/RegistrationRepositorySpec.scala
> Live handover | Update mongo dependency

- app/connectors/NonRepudiationConnector.scala
- it/test/repositories/RegistrationRepositorySpec.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/uk/gov/hmrc/plasticpackagingtaxregistration/base/it/ConnectorISpec.scala
> Dependency upgrades
